let print_rule eml =
  Printf.printf
    {|
(rule
 (target %s.ml)
 (action
  (run
   %%{bin:dream_eml}
   %%{dep:%s.eml}
   --workspace
   %%{workspace_root})))
|}
    eml eml

let () =
  print_endline ";; automatically generated by rulegen.ml, do not edit manually";
  Sys.readdir "." |> Array.to_seq
  |> Seq.filter_map (Filename.chop_suffix_opt ~suffix:".eml")
  |> List.of_seq |> List.sort String.compare |> List.iter print_rule
