(** This module enables parsing the `status.json` file generated by
    ocaml-docs-ci. If the documentation generation is successful, this file
    should exist and contain info about the other pages present in the package. *)

type redirection = { old_path : string; new_path : string } [@@deriving yojson]

type t = {
  name : string;
  version : string;
  failed : bool;
  files : string list;
  redirections : redirection list;
}
[@@deriving yojson]

val readme : t -> string option
val license : t -> string option
val changelog : t -> string option
val is_special : string -> bool
