let milestonesContentEn: Milestones.t = {
  items: [
    {
      version: Some("v3.1"),
      description: "Select technologies",
      period: "Nov - Jan 2020",
      completion: "100%",
      results: "Selected NextJS as static site generator, ReScript as implementation language, FlowMapp as sitemap tool, Figma for design, Tailwind for CSS.",
    },
    {
      version: Some("v3.2"),
      description: "Implement most important layouts",
      period: "Feb - Apr 2021",
      completion: "100%",
      results: "The 10 most important pages have been designed and implemented.",
    },
    {
      version: None,
      description: "Design information architecture",
      period: "Aug 2020 - Jun 2021",
      completion: "60%",
      results: " Sitemap is complete, 8 user personas and some journeys have been defined.",
    },
    {
      version: Some("v3.3"),
      description: "Implement all 40 distinct layouts",
      period: "Jun 30, 2021",
      completion: "25%",
      results: "A quarter of the 40 distinct pages have been implemented.",
    },
    {
      version: None,
      description: "Port 40 most important pages",
      period: "Aug 2021",
      completion: "10%",
      results: "Some work started.",
    },
    {
      version: Some("v3.4"),
      description: "Implement OCaml Manual",
      period: "Jul - Aug 2021",
      completion: "0%",
      results: "Not started.",
    },
    {
      version: Some("v3.5"),
      description: "Integrate docs.ocaml.org",
      period: "Jul 2021",
      completion: "0%",
      results: "Pending completion of the separate docs.ocaml.org project.",
    },
    {
      version: None,
      description: "Implement multilingual site framework",
      period: "Aug 2021",
      completion: "10%",
      results: "Some work started.",
    },
    {
      version: None,
      description: "Finalize site design",
      period: "Jan - Aug 2021",
      completion: "50%",
      results: "Half of the 40 pages needing a distinct design have been designed.",
    },
    {
      version: Some("v3.6"),
      description: "Go live on ocaml.org, replacing old site",
      period: "Aug 1, 2021",
      completion: "30%",
      results: "One-third of the work has been done.",
    },
  ],
}
