name: Docker Build and Release

on:
  workflow_dispatch:
    inputs:
      description: 'Branch to use'
      required: true
      default: 'main'
      type: choice

jobs:
  build-and-release:
    name: Build and push docker image to ghcr.io
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
