name: Scrape (OCaml Platform Releases)

on:
  workflow_dispatch:
  schedule:
    # Run every day
    - cron: 36 5 * * *

jobs:
  scrape:
    name: Run Scrapers
    if: github.event_name != 'schedule' || github.repository == 'ocaml/ocaml.org'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install runtime dependencies
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libev4 libonig5

      - name: Download scraper binary
        run: |
          gh release download scraper-latest --pattern scrape.exe
          chmod +x scrape.exe
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run scrapers
        run: make scrape_platform_releases SCRAPE=./scrape.exe

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          title: '[scrape_platform_releases.yml] New Platform Releases'
          labels: scrape
          branch: create-pull-request/patch-scrape-changelog
          add-paths: |
            data/**/*.md
          commit-message: |
            [scrape_platform_releases.yml] New Platform Releases
