name: Scrape (OCaml Changelog)

on:
  workflow_dispatch:
  schedule:
    # Run every day
    - cron: 36 5 * * *

jobs:
  scrape:
    name: Run Scrapers

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Setup Dune
        uses: ocaml-dune/setup-dune@v1
        with:
          version: 3.20.1

      - name: Install system dependencies
        run: sudo apt update && sudo apt-get install libev-dev libonig-dev libcurl4-openssl-dev

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run scraper
        run: |
          make scrape_platform_releases

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: '[scrape_platform_releases.yml] New Platform Releases'
          labels: scrape
          branch: create-pull-request/patch-scrape-changelog
          add-paths: |
            data/changelog/*/*.md
          commit-message: |
            [scrape_platform_releases.yml] New Platform Releases
